import type { Metadata } from "next"; import { ArticleShell } from "@/components/article-shell";
import { PracticalCasePanel } from "@/components/PracticalCasePanel";
import { createPageMetadata } from "@/lib/page-metadata";
export const metadata:Metadata=createPageMetadata("/pl-model", {title:"損益計算書（PL）のExcel設計",description:"M&Aモデルの損益計算書を前提条件から将来計画までExcelで構築する方法。"});
const sections=[{id:"layout",label:"シート構造"},{id:"revenue",label:"売上高計画"},{id:"cost",label:"費用計画"},{id:"formula",label:"Excel実装"},{id:"output",label:"出力連携"}];
export default function Page(){return <ArticleShell no="04" href="/pl-model" title="損益計算書（PL）のExcel設計" lead="売上高から当期純利益までを、事業ドライバーと前提条件から積み上げます。増減率を直接置くのではなく、計画を実現する数量・単価・人員を数式で示します。" sections={sections}>
<PracticalCasePanel stageId="pl" />
<h2 id="layout">損益計算書シートの行構成</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>行</th><th>勘定科目</th><th>予測方法</th><th>主な参照元</th></tr></thead><tbody><tr><td>10</td><td>売上高</td><td>数量×平均単価</td><td>前提条件、売上高計画</td></tr><tr><td>20</td><td>売上原価</td><td>材料費＋労務費＋製造経費</td><td>原価計画</td></tr><tr><td>21</td><td>売上総利益</td><td>売上高－売上原価</td><td>同一シート</td></tr><tr><td>30</td><td>販売費及び一般管理費</td><td>人件費＋その他経費</td><td>人員計画、費用前提</td></tr><tr><td>31</td><td>営業利益</td><td>売上総利益－販売費及び一般管理費</td><td>同一シート</td></tr><tr><td>40</td><td>経常利益</td><td>営業利益＋営業外収益－営業外費用</td><td>借入金計画</td></tr><tr><td>50</td><td>税引前当期純利益</td><td>経常利益＋特別損益</td><td>取引前提</td></tr><tr><td>60</td><td>当期純利益</td><td>税引前当期純利益－法人税等</td><td>税務前提</td></tr></tbody></table></div>
<h2 id="revenue">売上高の将来計画</h2><p>過去3期の数量、平均単価、顧客数などを再現した後、予測期間だけ前提条件シートを参照します。実績列と予測列の境界を一列に固定し、数式が混在しないようにします。</p><div className="formula">売上高計画!H12 = 売上高計画!H8 × 売上高計画!H9<br/>損益計算書!H10 = 売上高計画!H12</div><div className="callout"><strong>実務上の確認</strong><br/>売上高の増加に必要な営業人員、設備能力、在庫、運転資金が、費用計画と貸借対照表へ反映されているかを確認します。</div>
<h2 id="cost">費用を固定費と変動費に分ける</h2><p>売上原価率を一律で置くより、主要材料費は数量×単価、人件費は平均人員×一人当たり人件費で構築します。小額項目のみ売上高比率や直近実績で簡略化します。</p><div className="formula">人件費 = AVERAGE(期首人員, 期末人員) × 一人当たり人件費<br/>減価償却費 = 固定資産計画から参照<br/>支払利息 = 借入金計画の期中平均残高 × 適用金利</div>
<h2 id="formula">前提条件シートから数式を引く</h2><p>前提条件シートでは、B列に前提コード、C～E列に下振れ・基本・上振れ、H2に選択シナリオを置きます。損益計算書へ数値を直接入力しません。</p><div className="formula">=XLOOKUP($B10,前提条件!$B$10:$B$200,CHOOSECOLS(前提条件!$C$10:$E$200,前提条件!$H$2),0)<br/>=IFERROR(売上高計画!H$12,0)<br/>=SUM(H20:H29)<br/>=IF(H$50&gt;0,H$50*前提条件!H税率,0)</div><p>`XLOOKUP`は前提コードを検索し、`CHOOSECOLS`は選択シナリオの列を返します。`IFERROR`は入力不足を隠す目的で乱用せず、ゼロが妥当な箇所だけに限定します。</p>
<h2 id="output">アウトプットシートへ送る</h2><p>アウトプットシートは損益計算書の完成行だけを参照し、再計算しません。これにより、差異が出た場合の調査先が損益計算書へ一本化されます。</p><div className="formula">アウトプット!H15 = 損益計算書!H10  // 売上高<br/>アウトプット!H16 = 損益計算書!H31  // 営業利益<br/>アウトプット!H17 = 損益計算書!H31 / 損益計算書!H10  // 営業利益率</div>
</ArticleShell>}
