/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next"; import { ArticleShell } from "@/components/article-shell";
import { PracticalCasePanel } from "@/components/PracticalCasePanel";
import { createPageMetadata } from "@/lib/page-metadata";
export const metadata:Metadata=createPageMetadata("/bs-model", {title:"貸借対照表（BS）のExcel設計",description:"売掛金・棚卸資産・買掛金の回転日数、固定資産・借入金の増減明細、現金接続から貸借一致までをExcelで設計します。"}); const sections=[{id:"layout",label:"勘定科目構成"},{id:"working",label:"運転資本"},{id:"fixed",label:"固定資産・借入金"},{id:"rollforward",label:"残高更新"},{id:"check",label:"貸借一致"}];
export default function Page(){return <ArticleShell no="05" href="/bs-model" title="貸借対照表（BS）のExcel設計" lead="貸借対照表は売上高比率で一括予測せず、各残高の発生原因と増減明細を使って期末残高を計算します。現金預金を最後に接続し、貸借一致を検証します。" sections={sections}>
<PracticalCasePanel stageId="bs" />
<h2 id="layout">日本語勘定科目で構造を固定する</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>区分</th><th>主な勘定科目</th><th>予測方法</th></tr></thead><tbody><tr><td>流動資産</td><td>現金及び預金、売掛金、棚卸資産、その他流動資産</td><td>CF接続、回転日数</td></tr><tr><td>固定資産</td><td>有形固定資産、無形固定資産、投資その他の資産</td><td>増減明細</td></tr><tr><td>流動負債</td><td>買掛金、未払金、未払法人税等、短期借入金</td><td>回転日数、個別計画</td></tr><tr><td>固定負債</td><td>長期借入金、退職給付に係る負債</td><td>返済計画、個別計画</td></tr><tr><td>純資産</td><td>資本金、資本剰余金、利益剰余金</td><td>増減明細</td></tr></tbody></table></div>
<h2 id="working">運転資本を回転日数で予測する</h2><p>前提条件シートに売掛金回転日数、棚卸資産回転日数、買掛金回転日数を置きます。季節性が強い場合は月次売上高・月次売上原価を基礎にします。</p><div className="formula">売掛金 = 売上高 × 売掛金回転日数 ÷ 365<br/>棚卸資産 = 売上原価 × 棚卸資産回転日数 ÷ 365<br/>買掛金 = 売上原価 × 買掛金回転日数 ÷ 365</div><div className="formula">貸借対照表!H15 = 損益計算書!H10 * XLOOKUP("売掛金回転日数",前提条件!$B:$B,前提条件!H:H) / 365</div>
<h2 id="fixed">固定資産と借入金は別表で管理する</h2><p>有形固定資産は設備投資と減価償却、借入金は新規調達と返済を明細化します。期末残高を直接入力すると、キャッシュ・フロー計算書と支払利息が接続できません。</p><div className="formula">期末有形固定資産 = 期首有形固定資産 + 設備投資額 − 減価償却費 − 売却帳簿価額<br/>期末借入金 = 期首借入金 + 新規借入額 − 約定返済額 − 任意返済額</div>
<h2 id="rollforward">すべての残高をロールフォワードする</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>明細</th><th>2027年度</th><th>Excel式</th></tr></thead><tbody><tr><td>期首利益剰余金</td><td>前期末残高</td><td>=G42</td></tr><tr><td>当期純利益</td><td>損益計算書</td><td>=損益計算書!H60</td></tr><tr><td>配当金</td><td>前提条件</td><td>=-前提条件!H配当金</td></tr><tr><td>期末利益剰余金</td><td>上記合計</td><td>=SUM(H44:H46)</td></tr></tbody></table></div>
<h2 id="check">貸借一致チェック</h2><p>現金及び預金をキャッシュ・フロー計算書から参照した後、資産合計と負債純資産合計の差額を常時表示します。</p><div className="formula">貸借一致チェック = 資産合計 − 負債純資産合計<br/>=IF(ABS(H55-H95)&lt;0.1,"正常","要確認")</div><div className="callout warning"><strong>差額を雑勘定で埋めない</strong><br/>差額が発生した最初の年度を特定し、利益剰余金、現金増減、固定資産増減、借入金返済の順に接続を確認します。</div>
</ArticleShell>}
